['coca_leaf'] 		= {['name'] = 'coca_leaf', 			['label'] = 'Coke Leaf', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'coca_leaf.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Cocaine leaf'},
['coke_cutted'] 	= {['name'] = 'coke_cutted', 		['label'] = 'Cutted Coke', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'coke_cutted.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Cutted cocaine'},
['coke_packaged'] 	= {['name'] = 'coke_packaged', 		['label'] = 'Packaged Coke', 		['weight'] = 0, ['type'] = 'item', ['image'] = 'coke_packaged.png', 	['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['description'] = 'Packaged cocaine'},

['meth_ingredient'] = {['name'] = 'meth_ingredient', 	['label'] = 'Meth Ingredients', 	['weight'] = 0, ['type'] = 'item', ['image'] = 'meth_ingredient.png', 	['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Meth ingredients'},
['meth_pure'] 		= {['name'] = 'meth_pure', 			['label'] = 'Pure Meth', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'meth_pure.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Pure meth'},
['meth_packaged'] 	= {['name'] = 'meth_packaged', 		['label'] = 'Packaged Meth', 		['weight'] = 0, ['type'] = 'item', ['image'] = 'meth_packaged.png', 	['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['description'] = 'Packed meth'},

['weed_leaf'] 		= {['name'] = 'weed_leaf', 			['label'] = 'Weed Leaf', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'weed_leaf.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Weed leaf'},
['weed_untrimmed'] 	= {['name'] = 'weed_untrimmed', 	['label'] = 'Untrimmed Weed', 		['weight'] = 0, ['type'] = 'item', ['image'] = 'weed_untrimmed.png', 	['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Untrimmed weed'},
['weed_packaged'] 	= {['name'] = 'weed_packaged', 		['label'] = 'Packaged Weed', 		['weight'] = 0, ['type'] = 'item', ['image'] = 'weed_packaged.png', 	['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['description'] = 'Packaged weed'},
['weed_joint'] 		= {['name'] = 'weed_joint', 		['label'] = 'Joint', 				['weight'] = 0, ['type'] = 'item', ['image'] = 'weed_joint.png', 		['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['description'] = 'Weed joint'},

['chemicals'] 		= {['name'] = 'chemicals', 			['label'] = 'Chemicals', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'chemicals.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Chemicals'},
['hq_scale'] 		= {['name'] = 'hq_scale', 			['label'] = 'HQ Scale', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'hq_scale.png', 			['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'High quality scale'},
['plastic_bags'] 	= {['name'] = 'plastic_bags', 		['label'] = 'Plastic Bag', 			['weight'] = 0, ['type'] = 'item', ['image'] = 'plastic_bags.png', 		['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Plastic bag'},
['rolling_paper'] 	= {['name'] = 'rolling_paper', 		['label'] = 'Rolling Paper', 		['weight'] = 0, ['type'] = 'item', ['image'] = 'rolling_paper.png', 	['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Rolling papers'},